return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.18.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 100,
  height = 100,
  tilewidth = 16,
  tileheight = 16,
  nextobjectid = 1,
  backgroundcolor = { 0, 0, 0 },
  properties = {},
  tilesets = {
    {
      name = "roguelikeSheet_transparent",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 1,
      margin = 0,
      image = "roguelikeSheet_transparent.png",
      imagewidth = 968,
      imageheight = 526,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 1767,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Floor",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt1kkKwkAQBdAmOavicAG9mtOt1K0GzEKwSm1C6+I96E2gNvVJ/y4FAADg945dKfvknLrv56IZ3jvfd7fq43MJdn5N5s7yqDbsbtbHZxnsfJ3MyKPesLttic882Pmij2fkUe9dHpvkyGN68vgvUV+P76Qsj+iNdZVHtaivx3dSlkf0Nhu6njpRX88+zCPqeqb3SR60I4//knW93m4v63q93V7W9Xq7vd3jXnpl+H5wXzU1/h+v+D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODZDYyhh0A="
    },
    {
      type = "tilelayer",
      name = "Carpet",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt1skNwkAMBVBnObLUQSt0QS10QUJVhK0bfEQ5gCIFjYD3pK+5+GCNNfJEAAAAAMBv2FQRu6p0F/A9uibikG+my/SZY1O6o/825P2fcg5D5py5mEdRyzZiUeeZWWXWbemOoJxt/dl6ptlPvN+p9QBzGe+Da/5vb0+5N6/rmdd4H7ybh/0BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARD2/HE/E="
    },
    {
      type = "tilelayer",
      name = "Objects",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt1U1Kw0AYBuBJvUQRLHTlFfQm9ggue4UuLXgD0VWvYaGg4AnsuhfplEYacCaTYKSLPg+8fPMbhkAyIQAAAMBvd1UIL7F+hWMNjVqyq451FvMw+Mku07x+p1fVaex2dGq/ZeqPm5hJHf5uUZjfZuoysfZ5kBPRxWqUHt/EPFbpOforfR9dXMeMB3gO3bw3wv96LfQPPmI+Y+7r/9JTZn1qL/18F/oH60ba9qf2AnB5cveze/s8mvfzNDMOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbfYkoh2w"
    },
    {
      type = "tilelayer",
      name = "Details",
      x = 0,
      y = 0,
      width = 100,
      height = 100,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztziEBACAMAMEBMchICZJTYGJuiDvz9iMAAAAgt0deoObM7gMq7uo+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH7zAKpOAUk="
    }
  }
}
